const colors = {
  light: {
    text: "#0D1F0E",
    tint: "#1B4332",
    background: "#F8FAF5",
    foreground: "#0D1F0E",
    card: "#FFFFFF",
    cardForeground: "#0D1F0E",
    primary: "#1B4332",
    primaryForeground: "#FFFFFF",
    secondary: "#F4811E",
    secondaryForeground: "#FFFFFF",
    muted: "#EEF2E6",
    mutedForeground: "#6B7A6C",
    accent: "#F4811E",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#D8E6D0",
    input: "#E2EDD8",
    ring: "#1B4332",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#CA8A04",
    warningForeground: "#FFFFFF",
  },
  dark: {
    text: "#E8F0E9",
    tint: "#4ADE80",
    background: "#0A160C",
    foreground: "#E8F0E9",
    card: "#122016",
    cardForeground: "#E8F0E9",
    primary: "#2D6A4F",
    primaryForeground: "#FFFFFF",
    secondary: "#F4811E",
    secondaryForeground: "#FFFFFF",
    muted: "#1A2E1D",
    mutedForeground: "#8FA88F",
    accent: "#F4811E",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3520",
    input: "#1E3520",
    ring: "#2D6A4F",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#EAB308",
    warningForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
