import type { Category, Order, Product, User } from "@/types";

export const CATEGORIES: Category[] = [
  { id: "vegetables", name: "Légumes", icon: "leaf-outline", color: "#22C55E" },
  { id: "fruits", name: "Fruits", icon: "nutrition-outline", color: "#F59E0B" },
  { id: "grains", name: "Céréales", icon: "basket-outline", color: "#D97706" },
  { id: "livestock", name: "Bétail", icon: "paw-outline", color: "#EF4444" },
  { id: "fish", name: "Poisson", icon: "fish-outline", color: "#3B82F6" },
  { id: "processed", name: "Transformé", icon: "storefront-outline", color: "#8B5CF6" },
  { id: "dairy", name: "Laitier", icon: "water-outline", color: "#06B6D4" },
];

export const MOCK_CURRENT_USER: User = {
  id: "me",
  name: "Ibrahima Sow",
  email: "ibrahima@nafa.gn",
  phone: "+224 621 00 00 03",
  role: "customer",
  location: "Conakry, Guinée",
  verified: false,
  createdAt: "2024-06-01",
  stats: { listings: 0, sales: 0, orders: 8, rating: 4.5 },
};

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Mamadou Diallo",
    email: "mamadou@nafa.gn",
    phone: "+224 621 00 00 01",
    role: "farmer",
    location: "Kindia, Guinée",
    verified: true,
    createdAt: "2024-01-15",
    stats: { listings: 12, sales: 45, orders: 3, rating: 4.8 },
  },
  {
    id: "u2",
    name: "Fatoumata Bah",
    email: "fatoumata@nafa.gn",
    phone: "+224 621 00 00 02",
    role: "trader",
    location: "Conakry, Guinée",
    verified: true,
    createdAt: "2024-02-10",
    stats: { listings: 34, sales: 120, orders: 15, rating: 4.6 },
  },
  {
    id: "u3",
    name: "Alpha Barry",
    email: "alpha@nafa.gn",
    phone: "+224 621 00 00 04",
    role: "warehouse",
    location: "Labé, Guinée",
    verified: true,
    createdAt: "2024-03-01",
    stats: { listings: 8, sales: 30, orders: 2, rating: 4.9 },
  },
  {
    id: "u4",
    name: "Restaurant Le Marché",
    email: "lemarche@nafa.gn",
    phone: "+224 621 00 00 05",
    role: "restaurant",
    location: "Conakry, Guinée",
    verified: true,
    createdAt: "2024-01-20",
    stats: { listings: 5, sales: 90, orders: 200, rating: 4.7 },
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Tomates fraîches",
    description:
      "Tomates cultivées sans pesticides dans la région de Kindia. Idéales pour cuisiner ou consommer fraîches. Récoltées chaque matin.",
    price: 5000,
    unit: "kg",
    category: "vegetables",
    images: ["https://picsum.photos/seed/tomato123/400/400"],
    quantity: 200,
    available: 150,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Kindia",
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    createdAt: "2024-06-10",
  },
  {
    id: "p2",
    name: "Mangues Kent",
    description:
      "Mangues de la variété Kent, sucrées et juteuses. Provenant des vergers de Fouta Djallon. Sans produits chimiques.",
    price: 8000,
    unit: "kg",
    category: "fruits",
    images: ["https://picsum.photos/seed/mango456/400/400"],
    quantity: 500,
    available: 320,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Labé",
    rating: 4.9,
    reviewCount: 41,
    featured: true,
    createdAt: "2024-06-08",
  },
  {
    id: "p3",
    name: "Riz local paddy",
    description:
      "Riz paddy de la région de Boffa. Cultivé dans les plaines inondables selon les méthodes traditionnelles guinéennes.",
    price: 45000,
    unit: "bag",
    category: "grains",
    images: ["https://picsum.photos/seed/rice789/400/400"],
    quantity: 50,
    available: 35,
    sellerId: "u3",
    sellerName: "Alpha Barry",
    sellerRole: "warehouse",
    location: "Boffa",
    rating: 4.6,
    reviewCount: 18,
    featured: true,
    createdAt: "2024-06-05",
  },
  {
    id: "p4",
    name: "Poisson barracuda séché",
    description:
      "Barracuda séché et fumé selon la méthode traditionnelle. Pêché dans l'Atlantique. Riche en protéines.",
    price: 12000,
    unit: "kg",
    category: "fish",
    images: ["https://picsum.photos/seed/fish321/400/400"],
    quantity: 80,
    available: 60,
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    sellerRole: "trader",
    location: "Conakry",
    rating: 4.5,
    reviewCount: 12,
    featured: false,
    createdAt: "2024-06-09",
  },
  {
    id: "p5",
    name: "Oignons violets",
    description:
      "Oignons violets de qualité supérieure. Cultivés en plein air dans la région de Coyah. Parfaits pour les sauces guinéennes.",
    price: 6000,
    unit: "kg",
    category: "vegetables",
    images: ["https://picsum.photos/seed/onion654/400/400"],
    quantity: 300,
    available: 210,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Coyah",
    rating: 4.7,
    reviewCount: 33,
    featured: false,
    createdAt: "2024-06-07",
  },
  {
    id: "p6",
    name: "Ananas frais",
    description:
      "Ananas sucrés et parfumés récoltés de nos plantations de Kindia. Livrés le lendemain de la récolte.",
    price: 3000,
    unit: "piece",
    category: "fruits",
    images: ["https://picsum.photos/seed/pineapple987/400/400"],
    quantity: 150,
    available: 90,
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    sellerRole: "trader",
    location: "Kindia",
    rating: 4.8,
    reviewCount: 27,
    featured: false,
    createdAt: "2024-06-11",
  },
  {
    id: "p7",
    name: "Mil local",
    description:
      "Mil cultivé dans la Haute Guinée. Idéal pour la préparation du tô ou de la bouillie traditionnelle.",
    price: 25000,
    unit: "bag",
    category: "grains",
    images: ["https://picsum.photos/seed/millet111/400/400"],
    quantity: 100,
    available: 75,
    sellerId: "u3",
    sellerName: "Alpha Barry",
    sellerRole: "warehouse",
    location: "Kankan",
    rating: 4.4,
    reviewCount: 9,
    featured: false,
    createdAt: "2024-06-03",
  },
  {
    id: "p8",
    name: "Lait de vache frais",
    description:
      "Lait frais de vaches élevées en pâturage naturel du Fouta Djallon. Collecté chaque matin, livré le jour même.",
    price: 4000,
    unit: "liter",
    category: "dairy",
    images: ["https://picsum.photos/seed/milk222/400/400"],
    quantity: 200,
    available: 120,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Mamou",
    rating: 4.9,
    reviewCount: 15,
    featured: true,
    createdAt: "2024-06-12",
  },
  {
    id: "p9",
    name: "Huile de palme rouge",
    description:
      "Huile de palme rouge artisanale, pressée à froid. Riche en vitamines A et E. Conditionnée en bouteilles de 1L.",
    price: 18000,
    unit: "bottle",
    category: "processed",
    images: ["https://picsum.photos/seed/palmoil333/400/400"],
    quantity: 60,
    available: 45,
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    sellerRole: "trader",
    location: "Conakry",
    rating: 4.6,
    reviewCount: 21,
    featured: false,
    createdAt: "2024-06-06",
  },
  {
    id: "p10",
    name: "Piment rouge frais",
    description:
      "Piments rouges forts cultivés localement. Parfaits pour les sauces épicées, séchés ou consommés frais.",
    price: 7000,
    unit: "kg",
    category: "vegetables",
    images: ["https://picsum.photos/seed/chili444/400/400"],
    quantity: 80,
    available: 55,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "N'Zérékoré",
    rating: 4.5,
    reviewCount: 16,
    featured: false,
    createdAt: "2024-06-04",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord1",
    items: [
      { productId: "p1", productName: "Tomates fraîches", price: 5000, quantity: 5, unit: "kg" },
      { productId: "p5", productName: "Oignons violets", price: 6000, quantity: 2, unit: "kg" },
    ],
    totalAmount: 37000,
    status: "delivering",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    deliveryAddress: "Kaloum, Conakry",
    createdAt: "2024-06-12",
    updatedAt: "2024-06-13",
  },
  {
    id: "ord2",
    items: [
      { productId: "p3", productName: "Riz local paddy", price: 45000, quantity: 1, unit: "bag" },
    ],
    totalAmount: 45000,
    status: "delivered",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u3",
    sellerName: "Alpha Barry",
    deliveryAddress: "Kaloum, Conakry",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-03",
  },
  {
    id: "ord3",
    items: [
      { productId: "p2", productName: "Mangues Kent", price: 8000, quantity: 3, unit: "kg" },
      { productId: "p6", productName: "Ananas frais", price: 3000, quantity: 4, unit: "piece" },
    ],
    totalAmount: 36000,
    status: "confirmed",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    deliveryAddress: "Ratoma, Conakry",
    createdAt: "2024-06-13",
    updatedAt: "2024-06-13",
  },
  {
    id: "ord4",
    items: [
      { productId: "p9", productName: "Huile de palme rouge", price: 18000, quantity: 2, unit: "bottle" },
    ],
    totalAmount: 36000,
    status: "delivered",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    deliveryAddress: "Kaloum, Conakry",
    createdAt: "2024-05-25",
    updatedAt: "2024-05-27",
  },
  {
    id: "ord5",
    items: [
      { productId: "p4", productName: "Poisson barracuda séché", price: 12000, quantity: 2, unit: "kg" },
    ],
    totalAmount: 24000,
    status: "pending",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    deliveryAddress: "Matoto, Conakry",
    createdAt: "2024-06-14",
    updatedAt: "2024-06-14",
  },
];
