import type {
  Category,
  Job,
  MainCategory,
  MarketPrice,
  Order,
  Product,
  Property,
  Restaurant,
  ServiceProvider,
  User,
  Vehicle,
  Warehouse,
  PartnerOpportunity,
  PartnerReferral,
  PartnerSale,
  PartnerLeaderboardEntry,
} from "@/types";

export const CATEGORIES: Category[] = [
  { id: "vegetables", name: "Légumes", icon: "leaf-outline", color: "#16A34A" },
  { id: "fruits", name: "Fruits", icon: "nutrition-outline", color: "#F59E0B" },
  { id: "grains", name: "Céréales", icon: "basket-outline", color: "#D97706" },
  { id: "livestock", name: "Bétail", icon: "paw-outline", color: "#EF4444" },
  { id: "fish", name: "Poisson", icon: "fish-outline", color: "#3B82F6" },
  { id: "processed", name: "Transformé", icon: "storefront-outline", color: "#8B5CF6" },
  { id: "dairy", name: "Laitier", icon: "water-outline", color: "#06B6D4" },
];

export const MAIN_CATEGORIES: MainCategory[] = [
  { id: "agriculture", name: "Agriculture", icon: "leaf", color: "#16A34A", description: "Produits agricoles frais" },
  { id: "restaurants", name: "Restaurants", icon: "restaurant", color: "#EA580C", description: "Cuisine locale et internationale" },
  { id: "real-estate", name: "Immobilier", icon: "home", color: "#2563EB", description: "Maisons, appartements, terrains" },
  { id: "services", name: "Services", icon: "construct", color: "#7C3AED", description: "Artisans et professionnels" },
  { id: "vehicles", name: "Véhicules", icon: "car", color: "#475569", description: "Voitures, motos, camions" },
  { id: "logistics", name: "Logistique", icon: "cube", color: "#DC2626", description: "Transport et livraison" },
  { id: "jobs", name: "Emplois", icon: "briefcase", color: "#0891B2", description: "Offres d'emploi" },
  { id: "electronics", name: "Électronique", icon: "phone-portrait", color: "#6366F1", description: "Appareils et gadgets", comingSoon: true },
  { id: "fashion", name: "Mode", icon: "shirt", color: "#EC4899", description: "Vêtements et accessoires", comingSoon: true },
  { id: "home-furniture", name: "Maison", icon: "bed", color: "#0D9488", description: "Meubles et décoration", comingSoon: true },
  { id: "construction", name: "Construction", icon: "hammer", color: "#92400E", description: "Matériaux et équipements", comingSoon: true },
  { id: "other", name: "Autre", icon: "ellipsis-horizontal", color: "#64748B", description: "Divers" },
];

export const MARKET_PRICES: MarketPrice[] = [
  { id: "mp1", product: "Tomate fraîche", category: "vegetables", price: 5000, unit: "kg", trend: "up", trendPercent: 8, market: "Madina, Conakry" },
  { id: "mp2", product: "Oignon violet", category: "vegetables", price: 6000, unit: "kg", trend: "down", trendPercent: 5, market: "Madina, Conakry" },
  { id: "mp3", product: "Riz local", category: "grains", price: 45000, unit: "bag", trend: "stable", trendPercent: 0, market: "Sandervalia" },
  { id: "mp4", product: "Mangue Kent", category: "fruits", price: 8000, unit: "kg", trend: "up", trendPercent: 12, market: "Matoto" },
  { id: "mp5", product: "Mil", category: "grains", price: 25000, unit: "bag", trend: "down", trendPercent: 3, market: "Kankan" },
  { id: "mp6", product: "Poisson fumé", category: "fish", price: 12000, unit: "kg", trend: "stable", trendPercent: 0, market: "Boulbinet" },
  { id: "mp7", product: "Piment rouge", category: "vegetables", price: 7000, unit: "kg", trend: "up", trendPercent: 15, market: "Conakry" },
  { id: "mp8", product: "Ananas", category: "fruits", price: 3000, unit: "piece", trend: "down", trendPercent: 4, market: "Kindia" },
  { id: "mp9", product: "Huile de palme", category: "processed", price: 18000, unit: "liter", trend: "stable", trendPercent: 0, market: "Conakry" },
];

export const MOCK_CURRENT_USER: User = {
  id: "me",
  name: "Ibrahima Sow",
  email: "ibrahima@nafa.gn",
  phone: "+224 621 00 00 03",
  role: "customer",
  location: "Conakry, Guinée",
  verified: false,
  createdAt: "2024-06-01",
  stats: { listings: 0, sales: 0, orders: 8, rating: 4.5 },
};

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Mamadou Diallo",
    email: "mamadou@nafa.gn",
    phone: "+224 621 00 00 01",
    role: "farmer",
    location: "Kindia, Guinée",
    verified: true,
    createdAt: "2024-01-15",
    stats: { listings: 12, sales: 45, orders: 3, rating: 4.8 },
  },
  {
    id: "u2",
    name: "Fatoumata Bah",
    email: "fatoumata@nafa.gn",
    phone: "+224 621 00 00 02",
    role: "trader",
    location: "Conakry, Guinée",
    verified: true,
    createdAt: "2024-02-10",
    stats: { listings: 34, sales: 120, orders: 15, rating: 4.6 },
  },
  {
    id: "u3",
    name: "Alpha Barry",
    email: "alpha@nafa.gn",
    phone: "+224 621 00 00 04",
    role: "warehouse",
    location: "Labé, Guinée",
    verified: true,
    createdAt: "2024-03-01",
    stats: { listings: 8, sales: 30, orders: 2, rating: 4.9 },
  },
  {
    id: "u4",
    name: "Restaurant Le Marché",
    email: "lemarche@nafa.gn",
    phone: "+224 621 00 00 05",
    role: "restaurant",
    location: "Conakry, Guinée",
    verified: true,
    createdAt: "2024-01-20",
    stats: { listings: 5, sales: 90, orders: 200, rating: 4.7 },
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Tomates fraîches",
    description: "Tomates cultivées sans pesticides dans la région de Kindia. Idéales pour cuisiner ou consommer fraîches. Récoltées chaque matin.",
    price: 5000,
    unit: "kg",
    category: "vegetables",
    images: ["https://picsum.photos/seed/tomato_nafa1/400/400"],
    quantity: 200,
    available: 150,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Kindia",
    rating: 4.8,
    reviewCount: 24,
    featured: true,
    createdAt: "2024-06-10",
  },
  {
    id: "p2",
    name: "Mangues Kent",
    description: "Mangues de la variété Kent, sucrées et juteuses. Provenant des vergers de Fouta Djallon. Sans produits chimiques.",
    price: 8000,
    unit: "kg",
    category: "fruits",
    images: ["https://picsum.photos/seed/mango_nafa2/400/400"],
    quantity: 500,
    available: 320,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Labé",
    rating: 4.9,
    reviewCount: 41,
    featured: true,
    createdAt: "2024-06-08",
  },
  {
    id: "p3",
    name: "Riz local paddy",
    description: "Riz paddy de la région de Boffa. Cultivé dans les plaines inondables selon les méthodes traditionnelles guinéennes.",
    price: 45000,
    unit: "bag",
    category: "grains",
    images: ["https://picsum.photos/seed/rice_nafa3/400/400"],
    quantity: 50,
    available: 35,
    sellerId: "u3",
    sellerName: "Alpha Barry",
    sellerRole: "warehouse",
    location: "Boffa",
    rating: 4.6,
    reviewCount: 18,
    featured: true,
    createdAt: "2024-06-05",
  },
  {
    id: "p4",
    name: "Poisson barracuda séché",
    description: "Barracuda séché et fumé selon la méthode traditionnelle. Pêché dans l'Atlantique. Riche en protéines.",
    price: 12000,
    unit: "kg",
    category: "fish",
    images: ["https://picsum.photos/seed/fish_nafa4/400/400"],
    quantity: 80,
    available: 60,
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    sellerRole: "trader",
    location: "Conakry",
    rating: 4.5,
    reviewCount: 12,
    featured: false,
    createdAt: "2024-06-09",
  },
  {
    id: "p5",
    name: "Oignons violets",
    description: "Oignons violets de qualité supérieure. Cultivés en plein air dans la région de Coyah. Parfaits pour les sauces guinéennes.",
    price: 6000,
    unit: "kg",
    category: "vegetables",
    images: ["https://picsum.photos/seed/onion_nafa5/400/400"],
    quantity: 300,
    available: 210,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Coyah",
    rating: 4.7,
    reviewCount: 33,
    featured: false,
    createdAt: "2024-06-07",
  },
  {
    id: "p6",
    name: "Ananas frais",
    description: "Ananas sucrés et parfumés récoltés de nos plantations de Kindia. Livrés le lendemain de la récolte.",
    price: 3000,
    unit: "piece",
    category: "fruits",
    images: ["https://picsum.photos/seed/pineapple_nafa6/400/400"],
    quantity: 150,
    available: 90,
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    sellerRole: "trader",
    location: "Kindia",
    rating: 4.8,
    reviewCount: 27,
    featured: false,
    createdAt: "2024-06-11",
  },
  {
    id: "p7",
    name: "Mil local",
    description: "Mil cultivé dans la Haute Guinée. Idéal pour la préparation du tô ou de la bouillie traditionnelle.",
    price: 25000,
    unit: "bag",
    category: "grains",
    images: ["https://picsum.photos/seed/millet_nafa7/400/400"],
    quantity: 100,
    available: 75,
    sellerId: "u3",
    sellerName: "Alpha Barry",
    sellerRole: "warehouse",
    location: "Kankan",
    rating: 4.4,
    reviewCount: 9,
    featured: false,
    createdAt: "2024-06-03",
  },
  {
    id: "p8",
    name: "Lait de vache frais",
    description: "Lait frais de vaches élevées en pâturage naturel du Fouta Djallon. Collecté chaque matin, livré le jour même.",
    price: 4000,
    unit: "liter",
    category: "dairy",
    images: ["https://picsum.photos/seed/milk_nafa8/400/400"],
    quantity: 200,
    available: 120,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Mamou",
    rating: 4.9,
    reviewCount: 15,
    featured: true,
    createdAt: "2024-06-12",
  },
  {
    id: "p9",
    name: "Huile de palme rouge",
    description: "Huile de palme rouge artisanale, pressée à froid. Riche en vitamines A et E. Conditionnée en bouteilles de 1L.",
    price: 18000,
    unit: "bottle",
    category: "processed",
    images: ["https://picsum.photos/seed/palmoil_nafa9/400/400"],
    quantity: 60,
    available: 45,
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    sellerRole: "trader",
    location: "Conakry",
    rating: 4.6,
    reviewCount: 21,
    featured: false,
    createdAt: "2024-06-06",
  },
  {
    id: "p10",
    name: "Piment rouge frais",
    description: "Piments rouges forts cultivés localement. Parfaits pour les sauces épicées, séchés ou consommés frais.",
    price: 7000,
    unit: "kg",
    category: "vegetables",
    images: ["https://picsum.photos/seed/chili_nafa10/400/400"],
    quantity: 80,
    available: 55,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "N'Zérékoré",
    rating: 4.5,
    reviewCount: 16,
    featured: false,
    createdAt: "2024-06-04",
  },
  {
    id: "p11",
    name: "Bananes plantain",
    description: "Plantain mûrs des plantations de la Guinée Forestière. Idéaux pour l'alloco, la bouillie ou frits nature.",
    price: 4500,
    unit: "bunch",
    category: "fruits",
    images: ["https://picsum.photos/seed/plantain_nafa11/400/400"],
    quantity: 120,
    available: 80,
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    sellerRole: "trader",
    location: "N'Zérékoré",
    rating: 4.7,
    reviewCount: 19,
    featured: true,
    createdAt: "2024-06-13",
  },
  {
    id: "p12",
    name: "Gombo frais",
    description: "Gombo récolté à maturité parfaite. Fondamental dans la cuisine guinéenne. Vendu en botte fraîche.",
    price: 3500,
    unit: "bunch",
    category: "vegetables",
    images: ["https://picsum.photos/seed/gombo_nafa12/400/400"],
    quantity: 90,
    available: 70,
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    sellerRole: "farmer",
    location: "Kindia",
    rating: 4.6,
    reviewCount: 11,
    featured: false,
    createdAt: "2024-06-14",
  },
];

export const PARTNER_OPPORTUNITIES: PartnerOpportunity[] = [
  {
    id: "po1",
    title: "Riz local - Commission 5%",
    sellerName: "Mamadou Diallo",
    sector: "Agriculture",
    city: "Kindia",
    price: 450000,
    commissionRate: 5,
    estimatedEarnings: 22500,
    badge: "Agriculture",
    campaignType: "Livraison de 1 sac",
  },
  {
    id: "po2",
    title: "Tomates fraîches - Commission 8%",
    sellerName: "Fatoumata Bah",
    sector: "Agriculture",
    city: "Conakry",
    price: 5000,
    commissionRate: 8,
    estimatedEarnings: 400,
    badge: "Agriculture",
    campaignType: "1 kg acheté",
  },
  {
    id: "po3",
    title: "20 clients restaurant - 5 000 GNF",
    sellerName: "Restaurant Le Marché",
    sector: "Restaurants",
    city: "Conakry",
    price: 50000,
    commissionRate: 10,
    estimatedEarnings: 5000,
    badge: "Restaurants",
    campaignType: "Commande complétée",
  },
  {
    id: "po4",
    title: "Appartement location - 200 000 GNF",
    sellerName: "Alpha Barry",
    sector: "Immobilier",
    city: "Labé",
    price: 1000000,
    commissionRate: 20,
    estimatedEarnings: 200000,
    badge: "Immobilier",
    campaignType: "Signature de bail",
  },
  {
    id: "po5",
    title: "Électricien - 10 000 GNF",
    sellerName: "Service Pro Guinée",
    sector: "Services",
    city: "Conakry",
    price: 20000,
    commissionRate: 50,
    estimatedEarnings: 10000,
    badge: "Services",
    campaignType: "Mission réussie",
  },
  {
    id: "po6",
    title: "Mangues Kent - Commission 7%",
    sellerName: "Mamadou Diallo",
    sector: "Agriculture",
    city: "Labé",
    price: 8000,
    commissionRate: 7,
    estimatedEarnings: 560,
    badge: "Agriculture",
    campaignType: "1 kg vendu",
  },
];

export const PARTNER_REFERRALS: PartnerReferral[] = [
  {
    id: "pr1",
    clientName: "Aïssatou Camara",
    campaign: "Commande restaurant",
    referredAt: "2024-06-12",
    status: "Complétée",
    reward: 5000,
  },
  {
    id: "pr2",
    clientName: "Ibrahima Traoré",
    campaign: "Riz local",
    referredAt: "2024-06-10",
    status: "En attente",
    reward: 22500,
  },
  {
    id: "pr3",
    clientName: "Mariama Sow",
    campaign: "Location appartement",
    referredAt: "2024-06-09",
    status: "Complétée",
    reward: 200000,
  },
];

export const PARTNER_SALES: PartnerSale[] = [
  {
    id: "ps1",
    product: "Riz local - 1 sac",
    buyerName: "Kadia Bah",
    amount: 450000,
    commission: 22500,
    date: "2024-06-14",
    status: "Payé",
  },
  {
    id: "ps2",
    product: "Tomates fraîches - 2 kg",
    buyerName: "Oumar Camara",
    amount: 10000,
    commission: 800,
    date: "2024-06-13",
    status: "Payé",
  },
  {
    id: "ps3",
    product: "Électricien - mission",
    buyerName: "Fodè Sylla",
    amount: 20000,
    commission: 10000,
    date: "2024-06-11",
    status: "En attente",
  },
];

export const PARTNER_LEADERBOARD: PartnerLeaderboardEntry[] = [
  { id: "pl1", name: "Aminata Diallo", role: "Ambassadeur", earnings: 750000, rank: 1, badge: "Top Ambassador" },
  { id: "pl2", name: "Ousmane Keita", role: "Partenaire", earnings: 620000, rank: 2, badge: "Top Seller" },
  { id: "pl3", name: "Hawa Camara", role: "Partenaire", earnings: 510000, rank: 3, badge: "Trusted Farmer" },
  { id: "pl4", name: "Mamadou Traoré", role: "Partenaire", earnings: 420000, rank: 4, badge: "Trusted Business" },
  { id: "pl5", name: "Fatoumata Bah", role: "Partenaire", earnings: 390000, rank: 5, badge: "Verified Partner" },
];

export const PARTNER_EARNINGS_HISTORY = [
  { id: "eh1", label: "Semaine 1", amount: 120000 },
  { id: "eh2", label: "Semaine 2", amount: 90000 },
  { id: "eh3", label: "Semaine 3", amount: 145000 },
  { id: "eh4", label: "Semaine 4", amount: 170000 },
];

export const PARTNER_STATS = {
  totalSales: 12,
  totalReferrals: 8,
  totalEarnings: 780000,
  ranking: "Top Ambassador",
  verifiedStatus: true,
};

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord1",
    items: [
      { productId: "p1", productName: "Tomates fraîches", price: 5000, quantity: 5, unit: "kg" },
      { productId: "p5", productName: "Oignons violets", price: 6000, quantity: 2, unit: "kg" },
    ],
    totalAmount: 37000,
    status: "delivering",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    deliveryAddress: "Kaloum, Conakry",
    createdAt: "2024-06-12",
    updatedAt: "2024-06-13",
  },
  {
    id: "ord2",
    items: [
      { productId: "p3", productName: "Riz local paddy", price: 45000, quantity: 1, unit: "bag" },
    ],
    totalAmount: 45000,
    status: "delivered",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u3",
    sellerName: "Alpha Barry",
    deliveryAddress: "Kaloum, Conakry",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-03",
  },
  {
    id: "ord3",
    items: [
      { productId: "p2", productName: "Mangues Kent", price: 8000, quantity: 3, unit: "kg" },
      { productId: "p6", productName: "Ananas frais", price: 3000, quantity: 4, unit: "piece" },
    ],
    totalAmount: 36000,
    status: "confirmed",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u1",
    sellerName: "Mamadou Diallo",
    deliveryAddress: "Ratoma, Conakry",
    createdAt: "2024-06-13",
    updatedAt: "2024-06-13",
  },
  {
    id: "ord4",
    items: [
      { productId: "p9", productName: "Huile de palme rouge", price: 18000, quantity: 2, unit: "bottle" },
    ],
    totalAmount: 36000,
    status: "delivered",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    deliveryAddress: "Kaloum, Conakry",
    createdAt: "2024-05-25",
    updatedAt: "2024-05-27",
  },
  {
    id: "ord5",
    items: [
      { productId: "p4", productName: "Poisson barracuda séché", price: 12000, quantity: 2, unit: "kg" },
    ],
    totalAmount: 24000,
    status: "pending",
    buyerId: "me",
    buyerName: "Ibrahima Sow",
    sellerId: "u2",
    sellerName: "Fatoumata Bah",
    deliveryAddress: "Matoto, Conakry",
    createdAt: "2024-06-14",
    updatedAt: "2024-06-14",
  },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Le Saveur de Guinée",
    description: "Cuisine traditionnelle guinéenne authentique. Spécialités de Conakry, plats du terroir et boissons locales.",
    cuisine: "guinean",
    address: "Avenue de la République, Kaloum",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa1/600/400"],
    rating: 4.8,
    reviewCount: 142,
    priceRange: 2,
    deliveryTime: 35,
    deliveryFee: 5000,
    featured: true,
    isOpen: true,
    phone: "+224 622 11 22 33",
    menu: [
      { id: "m1", name: "Riz sauce arachide", description: "Riz basmati, poulet, sauce arachide maison", price: 35000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa1/300/200", popular: true },
      { id: "m2", name: "Fouti au gombo", description: "Fouti classique avec sauce gombo et poisson fumé", price: 28000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa2/300/200", popular: true },
      { id: "m3", name: "Brochettes mixtes", description: "Bœuf et agneau marinés, grillés au charbon", price: 42000, category: "Grillades", image: "https://picsum.photos/seed/dish_nafa3/300/200", popular: false },
      { id: "m4", name: "Jus de gingembre", description: "Jus de gingembre frais, citron et miel", price: 8000, category: "Boissons", image: "https://picsum.photos/seed/drink_nafa1/300/200", popular: true },
    ],
  },
  {
    id: "r2",
    name: "Chez Mamadou BBQ",
    description: "Grillades au charbon de bois, viandes fraîches du marché. Ambiance conviviale au cœur de Ratoma.",
    cuisine: "bbq",
    address: "Carrefour Hafia, Ratoma",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa2/600/400"],
    rating: 4.6,
    reviewCount: 89,
    priceRange: 1,
    deliveryTime: 25,
    deliveryFee: 3000,
    featured: true,
    isOpen: true,
    phone: "+224 622 44 55 66",
    menu: [
      { id: "m5", name: "Poulet braisé entier", description: "Poulet local grillé entier, accompagné d'attiéké", price: 85000, category: "Grillades", image: "https://picsum.photos/seed/dish_nafa5/300/200", popular: true },
      { id: "m6", name: "Côtelettes d'agneau", description: "Côtelettes marinées aux épices locales", price: 55000, category: "Grillades", image: "https://picsum.photos/seed/dish_nafa6/300/200", popular: true },
      { id: "m7", name: "Plantain frit", description: "Alloco maison, servi avec sauce piment", price: 12000, category: "Accompagnements", image: "https://picsum.photos/seed/dish_nafa7/300/200", popular: false },
    ],
  },
  {
    id: "r3",
    name: "Beirut Palace",
    description: "Restaurant libanais authentique avec mezzés, grillades et pâtisseries orientales. Le meilleur houmous de Conakry.",
    cuisine: "lebanese",
    address: "Rue KA-027, Kaloum",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa3/600/400"],
    rating: 4.7,
    reviewCount: 63,
    priceRange: 3,
    deliveryTime: 45,
    deliveryFee: 8000,
    featured: true,
    isOpen: true,
    phone: "+224 622 77 88 99",
    menu: [
      { id: "m8", name: "Plateau mezzés", description: "Houmous, taboulé, fatouche, falafel", price: 65000, category: "Entrées", image: "https://picsum.photos/seed/dish_nafa8/300/200", popular: true },
      { id: "m9", name: "Chawarma poulet", description: "Pain pita, poulet mariné, légumes frais", price: 38000, category: "Sandwichs", image: "https://picsum.photos/seed/dish_nafa9/300/200", popular: true },
    ],
  },
  {
    id: "r4",
    name: "La Terrasse Labé",
    description: "Restaurant panoramique surplombant la ville de Labé. Spécialités du Fouta Djallon et cuisine internationale.",
    cuisine: "mixed",
    address: "Centre-ville",
    city: "Labé",
    images: ["https://picsum.photos/seed/rest_nafa4/600/400"],
    rating: 4.5,
    reviewCount: 47,
    priceRange: 2,
    deliveryTime: 30,
    deliveryFee: 5000,
    featured: false,
    isOpen: true,
    phone: "+224 628 11 22 33",
    menu: [
      { id: "m10", name: "Poulet au yassa", description: "Poulet mijoté aux oignons et citron, riz parfumé", price: 40000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa10/300/200", popular: true },
      { id: "m10b", name: "Thiéboudienne", description: "Riz au poisson sénégalais, légumes frais", price: 35000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa10b/300/200", popular: true },
    ],
  },
  {
    id: "r5",
    name: "Fast NAFA Burger",
    description: "Burgers artisanaux, frites maison et milkshakes. La restauration rapide de qualité à Conakry.",
    cuisine: "fastfood",
    address: "Boulevard Diallo Telli, Madina",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa5/600/400"],
    rating: 4.3,
    reviewCount: 211,
    priceRange: 1,
    deliveryTime: 20,
    deliveryFee: 3000,
    featured: false,
    isOpen: true,
    phone: "+224 620 33 44 55",
    menu: [
      { id: "m11", name: "NAFA Burger Classic", description: "Pain brioche, bœuf local, cheddar, tomate", price: 32000, category: "Burgers", image: "https://picsum.photos/seed/dish_nafa11/300/200", popular: true },
      { id: "m12", name: "Frites maison large", description: "Pommes de terre fraîches, sauce secrète", price: 15000, category: "Accompagnements", image: "https://picsum.photos/seed/dish_nafa12/300/200", popular: true },
    ],
  },
  {
    id: "r6",
    name: "Café des Artistes",
    description: "Café moderne au cœur de Kaloum. Spécialités café guinéen, pâtisseries maison, petits-déjeuners copieux.",
    cuisine: "cafe",
    address: "Rue du Commerce, Kaloum",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa6/600/400"],
    rating: 4.4,
    reviewCount: 76,
    priceRange: 2,
    deliveryTime: 15,
    deliveryFee: 2000,
    featured: true,
    isOpen: true,
    phone: "+224 621 66 77 88",
    menu: [
      { id: "m13", name: "Café guinéen épicé", description: "Café local avec gingembre et cardamome", price: 8000, category: "Boissons", image: "https://picsum.photos/seed/drink_nafa2/300/200", popular: true },
      { id: "m14", name: "Croissant beurre", description: "Croissant français croustillant, beurre maison", price: 12000, category: "Pâtisseries", image: "https://picsum.photos/seed/dish_nafa13/300/200", popular: true },
      { id: "m15", name: "Omelette paysanne", description: "Œufs, oignons, tomates, piment, fromage", price: 18000, category: "Petit-déjeuner", image: "https://picsum.photos/seed/dish_nafa14/300/200", popular: false },
    ],
  },
  {
    id: "r7",
    name: "Diallo Poisson Grillé",
    description: "Spécialiste du poisson grillé frais de l'Atlantique. Méthode traditionnelle, servie avec riz et attiéké.",
    cuisine: "guinean",
    address: "Plage de Boulbinet",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa7/600/400"],
    rating: 4.9,
    reviewCount: 198,
    priceRange: 2,
    deliveryTime: 40,
    deliveryFee: 5000,
    featured: true,
    isOpen: true,
    phone: "+224 622 99 00 11",
    menu: [
      { id: "m16", name: "Barracuda grillé", description: "Barracuda entier, épices locales, citron", price: 55000, category: "Poissons", image: "https://picsum.photos/seed/dish_nafa15/300/200", popular: true },
      { id: "m17", name: "Capitaine sauce tomate", description: "Capitaine frais, sauce tomate maison, riz", price: 48000, category: "Poissons", image: "https://picsum.photos/seed/dish_nafa16/300/200", popular: true },
      { id: "m18", name: "Crevettes sautées", description: "Crevettes fraîches à l'ail et beurre", price: 65000, category: "Fruits de mer", image: "https://picsum.photos/seed/dish_nafa17/300/200", popular: false },
    ],
  },
  {
    id: "r8",
    name: "Maquis Chez Aminata",
    description: "Maquis populaire de Ratoma, cuisine familiale africaine. Riz, foufou, sauce gombo, et ambiance authentique.",
    cuisine: "guinean",
    address: "Quartier Dixinn",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa8/600/400"],
    rating: 4.5,
    reviewCount: 134,
    priceRange: 1,
    deliveryTime: 30,
    deliveryFee: 3000,
    featured: false,
    isOpen: true,
    phone: "+224 628 33 44 55",
    menu: [
      { id: "m19", name: "Foufou sauce arachide", description: "Foufou traditionnel, sauce arachide et viande", price: 22000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa18/300/200", popular: true },
      { id: "m20", name: "Riz blanc sauce gombo", description: "Riz blanc, sauce gombo, poisson fumé, épices", price: 20000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa19/300/200", popular: true },
    ],
  },
  {
    id: "r9",
    name: "Le Sénégalais",
    description: "Restaurant sénégalais authentique. Thiéboudienne, yassa, mafé. La cuisine de Dakar à Conakry.",
    cuisine: "senegalese",
    address: "Avenue Patrice Lumumba, Kaloum",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa9/600/400"],
    rating: 4.6,
    reviewCount: 58,
    priceRange: 2,
    deliveryTime: 35,
    deliveryFee: 6000,
    featured: false,
    isOpen: false,
    phone: "+224 621 55 66 77",
    menu: [
      { id: "m21", name: "Thiéboudienne rouge", description: "Riz au poisson sénégalais, légumes variés", price: 38000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa20/300/200", popular: true },
      { id: "m22", name: "Mafé bœuf", description: "Bœuf en sauce arachide épaisse, riz basmati", price: 42000, category: "Plats principaux", image: "https://picsum.photos/seed/dish_nafa21/300/200", popular: true },
    ],
  },
  {
    id: "r10",
    name: "Pizza Roma Conakry",
    description: "Pizzeria italienne avec four à bois. Pâtes fraîches maison, pizzas napolitaines, tiramisu artisanal.",
    cuisine: "mixed",
    address: "Cité des Nations",
    city: "Conakry",
    images: ["https://picsum.photos/seed/rest_nafa10/600/400"],
    rating: 4.2,
    reviewCount: 44,
    priceRange: 3,
    deliveryTime: 50,
    deliveryFee: 8000,
    featured: false,
    isOpen: true,
    phone: "+224 622 88 99 00",
    menu: [
      { id: "m23", name: "Pizza Margherita", description: "Tomate, mozzarella, basilic frais", price: 55000, category: "Pizzas", image: "https://picsum.photos/seed/dish_nafa22/300/200", popular: true },
      { id: "m24", name: "Spaghetti bolognaise", description: "Pâtes fraîches, sauce bolognaise maison", price: 45000, category: "Pâtes", image: "https://picsum.photos/seed/dish_nafa23/300/200", popular: false },
    ],
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "prop1",
    title: "Villa moderne à Kipé",
    description: "Magnifique villa de 4 chambres avec piscine, jardin paysager et vue sur l'Atlantique. Matériaux haut de gamme, finitions impeccables. Quartier résidentiel sécurisé.",
    type: "house",
    price: 350000000,
    priceType: "sale",
    surface: 280,
    bedrooms: 4,
    bathrooms: 3,
    address: "Résidence Les Palmiers, Kipé",
    city: "Conakry",
    images: ["https://picsum.photos/seed/house_nafa1/600/400"],
    rating: 4.9,
    featured: true,
    agentName: "Mamadou Kouyaté",
    agentPhone: "+224 621 50 50 50",
    createdAt: "2024-06-01",
  },
  {
    id: "prop2",
    title: "Appartement T3 Kaloum",
    description: "Appartement moderne au 5ème étage avec terrasse. Vue sur la mer. Parking sécurisé, gardiennage 24h/24. Idéal pour professionnels.",
    type: "apartment",
    price: 2500000,
    priceType: "rent",
    surface: 95,
    bedrooms: 3,
    bathrooms: 2,
    address: "Immeuble Horizon, Avenue de la République",
    city: "Conakry",
    images: ["https://picsum.photos/seed/apt_nafa1/600/400"],
    rating: 4.6,
    featured: true,
    agentName: "Aissatou Camara",
    agentPhone: "+224 628 60 60 60",
    createdAt: "2024-06-05",
  },
  {
    id: "prop3",
    title: "Terrain constructible Ratoma",
    description: "Terrain plat de 500m² avec titre foncier. Accès goudronné, eau et électricité disponibles. Zone résidentielle en pleine expansion.",
    type: "land",
    price: 120000000,
    priceType: "sale",
    surface: 500,
    address: "Quartier Hafia II",
    city: "Conakry",
    images: ["https://picsum.photos/seed/land_nafa1/600/400"],
    featured: false,
    agentName: "Ibrahim Sylla",
    agentPhone: "+224 622 70 70 70",
    createdAt: "2024-05-20",
  },
  {
    id: "prop4",
    title: "Maison familiale Kindia",
    description: "Belle maison de 3 chambres en plein centre de Kindia. Cour intérieure, cuisine équipée, garage. Proximité marchés et écoles.",
    type: "house",
    price: 85000000,
    priceType: "sale",
    surface: 160,
    bedrooms: 3,
    bathrooms: 2,
    address: "Centre-ville",
    city: "Kindia",
    images: ["https://picsum.photos/seed/house_nafa2/600/400"],
    featured: false,
    agentName: "Ousmane Diallo",
    agentPhone: "+224 621 80 80 80",
    createdAt: "2024-06-08",
  },
  {
    id: "prop5",
    title: "Local commercial Madina",
    description: "Local commercial de 120m² en bordure du grand marché de Madina. Fort passage, vitrines, arrière-boutique. Bail commercial disponible.",
    type: "commercial",
    price: 3500000,
    priceType: "rent",
    surface: 120,
    address: "Grand Marché de Madina",
    city: "Conakry",
    images: ["https://picsum.photos/seed/commercial_nafa1/600/400"],
    featured: true,
    agentName: "Fatoumata Bah",
    agentPhone: "+224 622 90 90 90",
    createdAt: "2024-06-10",
  },
  {
    id: "prop6",
    title: "Villa avec vue mer Nongo",
    description: "Somptueuse villa en bord de mer. Accès direct à la plage, terrasse panoramique, 5 suites climatisées. Idéale pour résidence principale ou investissement.",
    type: "house",
    price: 650000000,
    priceType: "sale",
    surface: 450,
    bedrooms: 5,
    bathrooms: 4,
    address: "Plage de Nongo",
    city: "Conakry",
    images: ["https://picsum.photos/seed/villa_nafa2/600/400"],
    rating: 5.0,
    featured: true,
    agentName: "Sekou Touré",
    agentPhone: "+224 624 10 10 10",
    createdAt: "2024-06-12",
  },
  {
    id: "prop7",
    title: "Studio meublé Dixinn",
    description: "Studio entièrement meublé, climatisé, internet haut débit. Idéal pour étudiant ou professionnel en déplacement. Charges comprises.",
    type: "apartment",
    price: 800000,
    priceType: "rent",
    surface: 35,
    bedrooms: 1,
    bathrooms: 1,
    address: "Quartier Dixinn",
    city: "Conakry",
    images: ["https://picsum.photos/seed/studio_nafa1/600/400"],
    featured: false,
    agentName: "Mariama Sow",
    agentPhone: "+224 621 20 20 20",
    createdAt: "2024-06-09",
  },
  {
    id: "prop8",
    title: "Grande maison Labé",
    description: "Spacieuse maison de 5 chambres à Labé. Cour arborée, bassin, cuisine d'été, 2 garages. Idéale pour famille nombreuse.",
    type: "house",
    price: 130000000,
    priceType: "sale",
    surface: 320,
    bedrooms: 5,
    bathrooms: 3,
    address: "Quartier Commercial",
    city: "Labé",
    images: ["https://picsum.photos/seed/house_nafa3/600/400"],
    featured: true,
    agentName: "Boubacar Bah",
    agentPhone: "+224 628 40 40 40",
    createdAt: "2024-06-03",
  },
  {
    id: "prop9",
    title: "Entrepôt Kagbélen",
    description: "Entrepôt de 800m² en zone industrielle. Quai de chargement, bureau, gardiennage. Accessible poids lourds. Idéal pour commerce ou industrie.",
    type: "warehouse",
    price: 5000000,
    priceType: "rent",
    surface: 800,
    address: "Zone Industrielle Kagbélen",
    city: "Conakry",
    images: ["https://picsum.photos/seed/warehouse_nafa1/600/400"],
    featured: false,
    agentName: "Ibrahima Camara",
    agentPhone: "+224 622 50 50 50",
    createdAt: "2024-05-28",
  },
  {
    id: "prop10",
    title: "Appartement T2 Matoto",
    description: "Appartement 2 pièces rénové, cuisine équipée, balcon. Immeuble sécurisé avec ascenseur. Proche transports et commerces.",
    type: "apartment",
    price: 1500000,
    priceType: "rent",
    surface: 65,
    bedrooms: 2,
    bathrooms: 1,
    address: "Immeuble Central, Matoto",
    city: "Conakry",
    images: ["https://picsum.photos/seed/apt_nafa2/600/400"],
    featured: false,
    agentName: "Aminata Diallo",
    agentPhone: "+224 621 30 30 30",
    createdAt: "2024-06-11",
  },
];

export const MOCK_SERVICES: ServiceProvider[] = [
  {
    id: "svc1",
    name: "Diallo Auto Service",
    category: "mechanics",
    description: "Mécanique générale, vidange, révision, réparation électronique. Spécialiste Toyota et Renault. Pièces d'origine disponibles.",
    city: "Conakry",
    phone: "+224 621 15 15 15",
    rating: 4.8,
    reviewCount: 87,
    price: 50000,
    priceType: "per_job",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/mec_nafa1/300/300",
    skills: ["Toyota", "Renault", "Climatisation", "Électronique auto"],
  },
  {
    id: "svc2",
    name: "ElectroPro Guinée",
    category: "electrician",
    description: "Installation électrique résidentielle et industrielle. Tableau électrique, climatiseur, groupe électrogène. Intervention rapide.",
    city: "Conakry",
    phone: "+224 622 25 25 25",
    rating: 4.7,
    reviewCount: 56,
    price: 75000,
    priceType: "per_job",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/elec_nafa1/300/300",
    skills: ["Installation", "Dépannage", "Climatisation", "Groupe électrogène"],
  },
  {
    id: "svc3",
    name: "Plomberie Conakry",
    category: "plumber",
    description: "Plomberie générale, installation sanitaire, dépannage fuites. Disponible 7j/7. Devis gratuit.",
    city: "Conakry",
    phone: "+224 623 35 35 35",
    rating: 4.5,
    reviewCount: 34,
    price: 60000,
    priceType: "per_job",
    available: true,
    verified: false,
    image: "https://picsum.photos/seed/plomb_nafa1/300/300",
    skills: ["Fuites", "Sanitaire", "Chauffe-eau", "Pompe à eau"],
  },
  {
    id: "svc4",
    name: "Tech Repair Guinée",
    category: "technician",
    description: "Réparation téléphones, ordinateurs, tablettes. Récupération de données, mise à niveau. Délai rapide, prix compétitifs.",
    city: "Conakry",
    phone: "+224 620 45 45 45",
    rating: 4.6,
    reviewCount: 112,
    price: 40000,
    priceType: "per_job",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/tech_nafa1/300/300",
    skills: ["iPhone", "Samsung", "MacBook", "Récupération données"],
  },
  {
    id: "svc5",
    name: "CleanPro Services",
    category: "cleaning",
    description: "Nettoyage résidentiel et professionnel. Ménage quotidien, grand ménage, nettoyage de bureaux. Équipe formée et discrète.",
    city: "Conakry",
    phone: "+224 621 55 55 55",
    rating: 4.9,
    reviewCount: 145,
    price: 35000,
    priceType: "per_job",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/clean_nafa1/300/300",
    skills: ["Ménage", "Bureaux", "Grand ménage", "Jardinage"],
  },
  {
    id: "svc6",
    name: "Bâ Transport Logistique",
    category: "transport",
    description: "Transport de marchandises Conakry et intérieur pays. Camionnette, camion 5T. Devis sur demande, suivi en temps réel.",
    city: "Conakry",
    phone: "+224 624 65 65 65",
    rating: 4.4,
    reviewCount: 29,
    price: 0,
    priceType: "negotiable",
    available: true,
    verified: false,
    image: "https://picsum.photos/seed/trans_nafa1/300/300",
    skills: ["Marchandises", "Déménagement", "Longue distance", "Réfrigéré"],
  },
  {
    id: "svc7",
    name: "Soudure Pro Conakry",
    category: "welder",
    description: "Soudure TIG, MIG, ARC. Fabrication métallique, portails, grilles, clôtures. Interventions sur chantier ou en atelier.",
    city: "Conakry",
    phone: "+224 621 75 75 75",
    rating: 4.6,
    reviewCount: 41,
    price: 80000,
    priceType: "per_job",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/welder_nafa1/300/300",
    skills: ["Soudure TIG", "Portails", "Grilles", "Charpente métallique"],
  },
  {
    id: "svc8",
    name: "Camara Construction",
    category: "construction",
    description: "Maçonnerie, carrelage, peinture, plâtrerie. Construction et rénovation. Équipe de 15 ouvriers qualifiés. Devis gratuit sous 24h.",
    city: "Conakry",
    phone: "+224 622 85 85 85",
    rating: 4.7,
    reviewCount: 63,
    price: 0,
    priceType: "negotiable",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/const_nafa1/300/300",
    skills: ["Maçonnerie", "Carrelage", "Peinture", "Rénovation"],
  },
  {
    id: "svc9",
    name: "Garde Sécurité Alpha",
    category: "security",
    description: "Gardiennage résidentiel et commercial. Agents formés, véhiculés. Rondes nocturnes. Contrat mensuel ou événementiel.",
    city: "Conakry",
    phone: "+224 628 95 95 95",
    rating: 4.3,
    reviewCount: 22,
    price: 200000,
    priceType: "per_job",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/secu_nafa1/300/300",
    skills: ["Gardiennage", "Rondes", "Événementiel", "Surveillance caméras"],
  },
  {
    id: "svc10",
    name: "Dev Web Freelance",
    category: "freelancer",
    description: "Développement de sites web, applications mobiles, gestion réseaux sociaux. Spécialiste e-commerce et marketplace.",
    city: "Conakry",
    phone: "+224 621 05 05 05",
    rating: 4.8,
    reviewCount: 37,
    price: 150000,
    priceType: "per_job",
    available: true,
    verified: true,
    image: "https://picsum.photos/seed/dev_nafa1/300/300",
    skills: ["React", "WordPress", "Mobile", "SEO"],
  },
  {
    id: "svc11",
    name: "Mécanique Barry Labé",
    category: "mechanics",
    description: "Mécanique générale toutes marques. Spécialiste véhicules 4x4. Pièces de rechange disponibles. Dépannage sur route.",
    city: "Labé",
    phone: "+224 628 05 06 07",
    rating: 4.5,
    reviewCount: 44,
    price: 45000,
    priceType: "per_job",
    available: true,
    verified: false,
    image: "https://picsum.photos/seed/mec_nafa2/300/300",
    skills: ["4x4", "Dépannage", "Pièces détachées", "Pneumatiques"],
  },
  {
    id: "svc12",
    name: "Électricité Kindia",
    category: "electrician",
    description: "Électricien certifié, installation solaire et réseau. Groupes électrogènes, panneaux photovoltaïques. Devis gratuit.",
    city: "Kindia",
    phone: "+224 621 14 15 16",
    rating: 4.6,
    reviewCount: 31,
    price: 70000,
    priceType: "per_job",
    available: false,
    verified: true,
    image: "https://picsum.photos/seed/elec_nafa2/300/300",
    skills: ["Solaire", "Groupe électrogène", "Installation", "Maintenance"],
  },
];

export const MOCK_WAREHOUSES: Warehouse[] = [
  {
    id: "wh1",
    name: "Entrepôt NAFA Kaloum",
    description: "Entrepôt moderne de 1500m² au cœur du port de Conakry. Température contrôlée, sécurité 24h/24, quai de chargement. Idéal pour import/export.",
    city: "Conakry",
    address: "Zone Portuaire, Kaloum",
    surfaceM2: 1500,
    pricePerMonth: 12000000,
    available: true,
    features: ["Climatisé", "Sécurisé 24h", "Quai de chargement", "Électricité industrielle", "Internet"],
    images: ["https://picsum.photos/seed/wh_nafa1/600/400"],
    ownerName: "NAFA Logistics",
    ownerPhone: "+224 621 90 90 90",
    rating: 4.8,
  },
  {
    id: "wh2",
    name: "Hangar Agricole Kindia",
    description: "Hangar de stockage pour produits agricoles. Ventilation naturelle, plancher béton, accès camions. Situé près du marché central de Kindia.",
    city: "Kindia",
    address: "Route de Mamou, km 2",
    surfaceM2: 800,
    pricePerMonth: 4500000,
    available: true,
    features: ["Ventilé", "Accès camions", "Gardiennage", "Bascule disponible"],
    images: ["https://picsum.photos/seed/wh_nafa2/600/400"],
    ownerName: "Coopérative Kindia",
    ownerPhone: "+224 628 20 20 20",
    rating: 4.5,
  },
  {
    id: "wh3",
    name: "Entrepôt Frigorifique Conakry",
    description: "Chambre froide professionnelle pour denrées périssables. Capacité 200 tonnes. Certifié normes internationales. Idéal pour poissons, viandes, produits laitiers.",
    city: "Conakry",
    address: "Zone Industrielle de Kagbélen",
    surfaceM2: 600,
    pricePerMonth: 18000000,
    available: false,
    features: ["Chambre froide -18°C", "Chambre positive +4°C", "Groupe électrogène", "Certification HACCP"],
    images: ["https://picsum.photos/seed/wh_nafa3/600/400"],
    ownerName: "Froid Guinée SA",
    ownerPhone: "+224 622 30 30 30",
    rating: 4.9,
  },
  {
    id: "wh4",
    name: "Dépôt Céréales Kankan",
    description: "Entrepôt spécialisé stockage céréales et légumineuses. Sacs et vrac. Situé en zone agricole de Haute Guinée.",
    city: "Kankan",
    address: "Route de Siguiri",
    surfaceM2: 1200,
    pricePerMonth: 3500000,
    available: true,
    features: ["Silos disponibles", "Traitement anti-nuisibles", "Accès camions", "Gardiennage nuit"],
    images: ["https://picsum.photos/seed/wh_nafa4/600/400"],
    ownerName: "Kouyaté Agri-Stock",
    ownerPhone: "+224 624 40 40 40",
    rating: 4.3,
  },
  {
    id: "wh5",
    name: "Mini-Entrepôt Matoto",
    description: "Petite surface idéale pour PME ou artisans. 200m², sécurisé, électricité incluse. Accès flexible 6h-22h tous les jours.",
    city: "Conakry",
    address: "Quartier Matoto, près du carrefour",
    surfaceM2: 200,
    pricePerMonth: 1800000,
    available: true,
    features: ["Électricité incluse", "Accès flexible", "Sécurisé", "Toilettes disponibles"],
    images: ["https://picsum.photos/seed/wh_nafa5/600/400"],
    ownerName: "Bah Immobilier",
    ownerPhone: "+224 621 60 60 60",
    rating: 4.1,
  },
];

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "v1",
    title: "Toyota Land Cruiser 200 - 2020",
    description: "Land Cruiser V8 en excellent état. Tout équipé : GPS, caméra de recul, toit ouvrant. Un seul propriétaire, entretien suivi chez concessionnaire.",
    type: "car",
    brand: "Toyota",
    model: "Land Cruiser 200",
    year: 2020,
    price: 180000000,
    priceType: "sale",
    mileage: 45000,
    fuel: "diesel",
    condition: "used",
    city: "Conakry",
    images: ["https://picsum.photos/seed/car_nafa1/600/400"],
    sellerName: "Mamadou Kouyaté",
    sellerPhone: "+224 621 11 22 33",
    rating: 4.9,
    featured: true,
    createdAt: "2024-06-01",
  },
  {
    id: "v2",
    title: "Toyota Hilux Double Cab - 2019",
    description: "Pick-up Hilux idéal pour l'intérieur pays. 4x4 permanent, benne protégée, climatisation. Robuste et fiable.",
    type: "truck",
    brand: "Toyota",
    model: "Hilux",
    year: 2019,
    price: 120000000,
    priceType: "sale",
    mileage: 78000,
    fuel: "diesel",
    condition: "used",
    city: "Conakry",
    images: ["https://picsum.photos/seed/car_nafa2/600/400"],
    sellerName: "Alpha Diallo",
    sellerPhone: "+224 622 33 44 55",
    rating: 4.7,
    featured: true,
    createdAt: "2024-06-05",
  },
  {
    id: "v3",
    title: "Honda CB 150 - Moto 2022",
    description: "Moto Honda CB 150cc en parfait état. Idéale pour livraison ou déplacements urbains. Faible consommation, entretien régulier.",
    type: "motorcycle",
    brand: "Honda",
    model: "CB 150",
    year: 2022,
    price: 12000000,
    priceType: "sale",
    mileage: 15000,
    fuel: "petrol",
    condition: "used",
    city: "Conakry",
    images: ["https://picsum.photos/seed/moto_nafa1/600/400"],
    sellerName: "Ibrahima Sow",
    sellerPhone: "+224 621 44 55 66",
    featured: false,
    createdAt: "2024-06-08",
  },
  {
    id: "v4",
    title: "Nissan Navara - 2021",
    description: "Nissan Navara double cab, boîte automatique, GPS intégré. Parfait état, première main. Idéal pour famille ou professionnel.",
    type: "truck",
    brand: "Nissan",
    model: "Navara",
    year: 2021,
    price: 100000000,
    priceType: "sale",
    mileage: 52000,
    fuel: "diesel",
    condition: "used",
    city: "Labé",
    images: ["https://picsum.photos/seed/car_nafa3/600/400"],
    sellerName: "Boubacar Barry",
    sellerPhone: "+224 628 55 66 77",
    rating: 4.5,
    featured: false,
    createdAt: "2024-06-10",
  },
  {
    id: "v5",
    title: "Renault Logan - 2018",
    description: "Berline Renault Logan, économique et fiable. Climatisation, vitres électriques, radio Bluetooth. Parfaite pour la ville.",
    type: "car",
    brand: "Renault",
    model: "Logan",
    year: 2018,
    price: 45000000,
    priceType: "sale",
    mileage: 89000,
    fuel: "petrol",
    condition: "used",
    city: "Conakry",
    images: ["https://picsum.photos/seed/car_nafa4/600/400"],
    sellerName: "Fatoumata Camara",
    sellerPhone: "+224 621 66 77 88",
    featured: false,
    createdAt: "2024-06-11",
  },
  {
    id: "v6",
    title: "Toyota Prado TX - 2017",
    description: "Land Cruiser Prado TX bien entretenu. 7 places, 4x4, climatisation automatique. Prêt à rouler.",
    type: "car",
    brand: "Toyota",
    model: "Prado TX",
    year: 2017,
    price: 130000000,
    priceType: "sale",
    mileage: 112000,
    fuel: "diesel",
    condition: "used",
    city: "Kindia",
    images: ["https://picsum.photos/seed/car_nafa5/600/400"],
    sellerName: "Ousmane Bah",
    sellerPhone: "+224 622 77 88 99",
    rating: 4.6,
    featured: true,
    createdAt: "2024-06-03",
  },
  {
    id: "v7",
    title: "Yamaha NMAX 155 - 2023",
    description: "Scooter Yamaha NMAX quasi neuf. Idéal pour livraisons rapides ou trajets quotidiens. Coffre sous selle, 2 casques inclus.",
    type: "motorcycle",
    brand: "Yamaha",
    model: "NMAX 155",
    year: 2023,
    price: 18000000,
    priceType: "sale",
    mileage: 5000,
    fuel: "petrol",
    condition: "used",
    city: "Conakry",
    images: ["https://picsum.photos/seed/moto_nafa2/600/400"],
    sellerName: "Sekou Konaté",
    sellerPhone: "+224 621 88 99 00",
    featured: false,
    createdAt: "2024-06-14",
  },
  {
    id: "v8",
    title: "Mercedes Sprinter - Minibus 2016",
    description: "Minibus Mercedes Sprinter 18 places. Parfait pour transport de personnel ou tourisme. Climatisé, entretien récent.",
    type: "van",
    brand: "Mercedes",
    model: "Sprinter",
    year: 2016,
    price: 85000000,
    priceType: "sale",
    mileage: 210000,
    fuel: "diesel",
    condition: "used",
    city: "Conakry",
    images: ["https://picsum.photos/seed/van_nafa1/600/400"],
    sellerName: "NAFA Transport",
    sellerPhone: "+224 622 00 11 22",
    rating: 4.2,
    featured: false,
    createdAt: "2024-06-02",
  },
  {
    id: "v9",
    title: "Pièces détachées Toyota disponibles",
    description: "Large stock de pièces d'origine et génériques pour Toyota Land Cruiser, Hilux, Prado. Filtres, amortisseurs, embrayages, freins.",
    type: "parts",
    brand: "Toyota",
    model: "Pièces diverses",
    year: 2024,
    price: 500000,
    priceType: "sale",
    condition: "new",
    city: "Conakry",
    images: ["https://picsum.photos/seed/parts_nafa1/600/400"],
    sellerName: "Auto Pièces Guinée",
    sellerPhone: "+224 621 10 20 30",
    featured: false,
    createdAt: "2024-06-06",
  },
];

export const MOCK_JOBS: Job[] = [
  {
    id: "j1",
    title: "Technicien agricole",
    company: "NAFA Market",
    description: "Nous recherchons un technicien agricole pour accompagner nos agriculteurs partenaires. Formation assurée. Véhicule de fonction fourni.",
    category: "agriculture",
    city: "Kindia",
    salary: 2500000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Bac+2 en agronomie", "Permis de conduire", "Expérience terrain 1 an minimum"],
    featured: true,
    postedAt: "2024-06-10",
    contactPhone: "+224 621 00 10 20",
    contactName: "Mamadou Barry",
    urgent: true,
  },
  {
    id: "j2",
    title: "Cuisinier(ère) - Restaurant guinéen",
    company: "Le Saveur de Guinée",
    description: "Restaurant traditionnel cherche cuisinier(ère) expérimenté(e). Maîtrise des plats guinéens indispensable. Service midi et soir.",
    category: "restaurant",
    city: "Conakry",
    salary: 1500000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Expérience cuisine guinéenne", "Ponctualité", "Sens de l'hygiène"],
    featured: true,
    postedAt: "2024-06-12",
    contactPhone: "+224 622 11 22 33",
    contactName: "Directeur RH",
    urgent: false,
  },
  {
    id: "j3",
    title: "Chauffeur livreur",
    company: "NAFA Express",
    description: "Conducteur de camionnette pour livraisons de produits agricoles en ville et banlieue. Permis B exigé. Connaissance de Conakry requise.",
    category: "transport",
    city: "Conakry",
    salary: 1200000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Permis B", "Connaissance Conakry", "Sérieux et ponctuel"],
    featured: true,
    postedAt: "2024-06-11",
    contactPhone: "+224 624 65 65 65",
    contactName: "Responsable flotte",
    urgent: true,
  },
  {
    id: "j4",
    title: "Maçon qualifié",
    company: "Camara Construction",
    description: "Nous recrutons des maçons expérimentés pour chantiers résidentiels à Conakry. Travaux de fondation, murs, finitions.",
    category: "construction",
    city: "Conakry",
    salary: 80000,
    salaryType: "per_day",
    contractType: "temporary",
    requirements: ["5 ans d'expérience minimum", "Autonomie", "Capacité de travail en équipe"],
    featured: false,
    postedAt: "2024-06-09",
    contactPhone: "+224 622 85 85 85",
    contactName: "Chef de chantier",
    urgent: false,
  },
  {
    id: "j5",
    title: "Serveur / Serveuse",
    company: "Café des Artistes",
    description: "Café moderne cherche serveur(se) souriant(e) et dynamique. Service en salle, préparation boissons simples. Formation assurée.",
    category: "restaurant",
    city: "Conakry",
    salary: 900000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Présentation soignée", "Bonne communication", "Débrouillardise"],
    featured: false,
    postedAt: "2024-06-13",
    contactPhone: "+224 621 66 77 88",
    contactName: "Gérant",
    urgent: true,
  },
  {
    id: "j6",
    title: "Agent de sécurité",
    company: "Garde Sécurité Alpha",
    description: "Agents de sécurité pour gardiennage résidentiel et commercial à Conakry. Formation de 3 jours offerte. Tenue fournie.",
    category: "security",
    city: "Conakry",
    salary: 800000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Bonne condition physique", "Casier judiciaire vierge", "Sérieux"],
    featured: false,
    postedAt: "2024-06-08",
    contactPhone: "+224 628 95 95 95",
    contactName: "Directeur sécurité",
    urgent: false,
  },
  {
    id: "j7",
    title: "Ouvrier agricole saisonnier",
    company: "Coopérative Kindia",
    description: "Recrutement d'ouvriers agricoles pour récolte de tomates et oignons. Durée 2 mois. Logement disponible sur place.",
    category: "agriculture",
    city: "Kindia",
    salary: 60000,
    salaryType: "per_day",
    contractType: "temporary",
    requirements: ["Bonne condition physique", "Disponible immédiatement", "Sérieux"],
    featured: false,
    postedAt: "2024-06-07",
    contactPhone: "+224 628 20 20 20",
    contactName: "Chef d'exploitation",
    urgent: true,
  },
  {
    id: "j8",
    title: "Technicien en téléphonie mobile",
    company: "Tech Repair Guinée",
    description: "Réparateur de téléphones et ordinateurs portables. Connaissances en micro-soudure appréciées. Salaire + commissions.",
    category: "tech",
    city: "Conakry",
    salary: 1800000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Formation électronique ou téléphonie", "Autonomie", "Rigueur"],
    featured: true,
    postedAt: "2024-06-14",
    contactPhone: "+224 620 45 45 45",
    contactName: "Directeur technique",
    urgent: false,
  },
  {
    id: "j9",
    title: "Aide cuisinière",
    company: "Maquis Chez Aminata",
    description: "Aide en cuisine pour maquis populaire. Épluchage, préparation, plonge. Repas fourni. Ambiance familiale.",
    category: "restaurant",
    city: "Conakry",
    salary: 700000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Motivation", "Hygiène irréprochable", "Disponibilité 6j/7"],
    featured: false,
    postedAt: "2024-06-06",
    contactPhone: "+224 628 33 44 55",
    contactName: "Aminata",
    urgent: false,
  },
  {
    id: "j10",
    title: "Commercial terrain",
    company: "NAFA Marché",
    description: "Agent commercial pour développer notre réseau d'agriculteurs et commerçants partenaires. Véhicule fourni. Salaire fixe + primes.",
    category: "trade",
    city: "Conakry",
    salary: 2000000,
    salaryType: "per_month",
    contractType: "full_time",
    requirements: ["Bac minimum", "Permis de conduire", "Excellente communication", "Autonomie"],
    featured: true,
    postedAt: "2024-06-15",
    contactPhone: "+224 621 00 00 01",
    contactName: "Directeur commercial NAFA",
    urgent: true,
  },
  {
    id: "j11",
    title: "Vendeur marchés agricoles",
    company: "NAFA Market",
    description: "Vendeur(se) pour stands agricoles aux marchés de Madina et Matoto. Bonne connaissance des produits locaux requise.",
    category: "agriculture",
    city: "Conakry",
    salary: 50000,
    salaryType: "per_day",
    contractType: "part_time",
    requirements: ["Connaissance produits agricoles", "Sens du commerce", "Disponible weekends"],
    featured: false,
    postedAt: "2024-06-13",
    contactPhone: "+224 621 00 00 02",
    contactName: "Responsable marchés",
    urgent: false,
  },
];

export const MOCK_OPPORTUNITIES = [
  {
    id: "opp1",
    title: "Devenir Vendeur NAFA Agriculture",
    description: "Rejoignez notre plateforme en tant que vendeur spécialisé en produits agricoles. Marges attractives et support marketing.",
    sector: "Agriculture",
    commission: 8,
    estimatedEarnings: 150000,
  },
  {
    id: "opp2",
    title: "Partenaire Restaurants Premium",
    description: "Restaurateurs: distribuez vos plats via NAFA. Visibilité accrue et clientèle prête à commander.",
    sector: "Restauration",
    commission: 12,
    estimatedEarnings: 200000,
  },
  {
    id: "opp3",
    title: "Agent Immobilier NAFA",
    description: "Commercialisez des propriétés sur notre plateforme. Commission intéressante par vente conclue.",
    sector: "Immobilier",
    commission: 5,
    estimatedEarnings: 250000,
  },
  {
    id: "opp4",
    title: "Prestataire de Services Certifié",
    description: "Menuisier, électricien, plombier... Listez vos services et toucheznos milliers de clients en quête de qualité.",
    sector: "Services",
    commission: 10,
    estimatedEarnings: 180000,
  },
];

export const MOCK_REFERRALS = [
  {
    id: "ref1",
    name: "Mamadou Touré",
    joinDate: "Juillet 2024",
    commissions: "12",
    sales: "45",
    status: "Actif",
  },
  {
    id: "ref2",
    name: "Aissatou Diallo",
    joinDate: "Juin 2024",
    commissions: "8",
    sales: "32",
    status: "Actif",
  },
  {
    id: "ref3",
    name: "Boubacar Bah",
    joinDate: "Août 2024",
    commissions: "15",
    sales: "58",
    status: "Actif",
  },
  {
    id: "ref4",
    name: "Fatou Kone",
    joinDate: "Septembre 2024",
    commissions: "6",
    sales: "18",
    status: "Inactif",
  },
];

export const MOCK_PARTNER_SALES = [
  {
    id: "ps1",
    orderId: "12345",
    date: "15 Sep 2024",
    productName: "Tomates fraîches (50kg)",
    quantity: 50,
    amount: 250000,
    status: "Complétée",
  },
  {
    id: "ps2",
    orderId: "12346",
    date: "14 Sep 2024",
    productName: "Riz local (100kg)",
    quantity: 100,
    amount: 4500000,
    status: "Complétée",
  },
  {
    id: "ps3",
    orderId: "12347",
    date: "14 Sep 2024",
    productName: "Mangues Kent (30kg)",
    quantity: 30,
    amount: 240000,
    status: "En attente",
  },
  {
    id: "ps4",
    orderId: "12348",
    date: "13 Sep 2024",
    productName: "Oignons violets (60kg)",
    quantity: 60,
    amount: 360000,
    status: "Complétée",
  },
];

export const MOCK_EARNINGS = [
  {
    id: "earn1",
    month: "Septembre 2024",
    source: "Ventes produits",
    amount: 1200000,
    period: "month",
  },
  {
    id: "earn2",
    month: "Août 2024",
    source: "Commissions",
    amount: 950000,
    period: "month",
  },
  {
    id: "earn3",
    month: "Juillet 2024",
    source: "Bonus partenaire",
    amount: 1050000,
    period: "month",
  },
  {
    id: "earn4",
    month: "Juin 2024",
    source: "Ventes produits",
    amount: 850000,
    period: "month",
  },
];

export const MOCK_LEADERBOARD = [
  {
    id: "lb1",
    name: "Alpha Diallo",
    role: "Vendeur Premium",
    earnings: 5200000,
  },
  {
    id: "lb2",
    name: "Fatoumata Bah",
    role: "Vendeur",
    earnings: 4850000,
  },
  {
    id: "lb3",
    name: "Mamadou Sow",
    role: "Vendeur",
    earnings: 4120000,
  },
  {
    id: "lb4",
    name: "Aissatou Kone",
    role: "Vendeur",
    earnings: 3650000,
  },
  {
    id: "lb5",
    name: "Boubacar Camara",
    role: "Partenaire",
    earnings: 3200000,
  },
  {
    id: "lb6",
    name: "Mariama Touré",
    role: "Partenaire",
    earnings: 2950000,
  },
];
