// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/auth/LoginElegant.tsx": () => import("../components/mockups/auth/LoginElegant.tsx"),
  "./components/mockups/auth/LoginPremium.tsx": () => import("../components/mockups/auth/LoginPremium.tsx"),
  "./components/mockups/auth/RegisterElegant.tsx": () => import("../components/mockups/auth/RegisterElegant.tsx"),
  "./components/mockups/auth/RegisterPremium.tsx": () => import("../components/mockups/auth/RegisterPremium.tsx")
};
